/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: packages/normalization-core/src/index.ts
// Public barrel for shared coercion and normalization helpers.

export * from "./number-coercion.js";
export * from "./record-coerce.js";
export * from "./string-coerce.js";
export * from "./string-normalization.js";
