/**
 * cindy-bridge —— 写进 pi agentHome/extensions/ 的扩展源码(字符串常量)。
 *
 * 这段代码跑在 **pi 子进程**(bun runtime)里,不能 import cindy 任何模块;
 * 只依赖 pi 的 ExtensionAPI、fetch 与 node:fs。职责:
 *  1. 权限门:tool_call 拦截。bypassPermissions 放行;ask 档下只读内置工具放行,
 *     其余(bash/edit/write + 全部桥接 MCP 工具)经 ctx.ui.confirm 走 cindy 审批
 *     (RPC 模式 → extension_ui_request → PiAgent → interactionResolver)。
 *     权限档从 CINDY_PI_PERMISSION_FILE 每次现读 —— setPermissionMode 热切换生效;
 *     读不到一律按 ask(fail-closed)。
 *  2. MCP 桥:CINDY_PI_MCP_BRIDGE 指向 host 的 localhost bridge，或用户显式配置的
 *     外部 Streamable HTTP MCP。外部认证只保存 env 引用，真值留在 Pi 父进程 env；
 *     对每个 server 走 initialize → 分页 tools/list,把工具注册成 pi 工具
 *     (mcp__<server>__<tool>),execute 转发 tools/call。
 *  3. 会话树:注册 Cindy 私有 command，把 RPC prompt 桥到 ctx.navigateTree。
 *
 * 协议说明(@modelcontextprotocol/sdk StreamableHTTPServerTransport):
 *  - POST 单条 JSON-RPC;Accept 必须同时含 application/json 与 text/event-stream;
 *  - initialize 响应头 mcp-session-id,后续请求回带;
 *  - 响应可能是 application/json 或 SSE(请求-响应模式下 server 发完即关流,
 *    text() 可整体读取后解析);notification 返回 202 空体。
 *
 * 更新方式:PiAgent 每次 startSession 覆写该文件;改这里 = 改下次会话的桥行为。
 */

import {
  REVIEW_SENSITIVE_CREDENTIAL_GLOB_PATTERNS,
  REVIEW_SENSITIVE_CREDENTIAL_PATH_PATTERN_SPECS,
  SENSITIVE_CREDENTIAL_PATH_PATTERN_SPECS,
} from "../shared/sensitive-credential-paths.js";

export const CINDY_BRIDGE_EXTENSION_FILENAME = "cindy-bridge.ts";

export const CINDY_BRIDGE_EXTENSION_SOURCE = String.raw`/**
 * cindy-bridge (generated by Cindy — do not edit; overwritten on session start)
 */
import { lstatSync, readFileSync, realpathSync, statSync } from 'node:fs';
import { stat } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { createInterface } from 'node:readline';
import path from 'node:path';
import {
  createBashTool,
  createFindTool,
  createGrepTool,
  createLsTool,
} from '@earendil-works/pi-coding-agent';

const PERMISSION_TITLE = 'cindy:permission';
const TURN_CHANGE_CAPTURE_TITLE = 'cindy:turn-change-capture';
const READONLY_BUILTINS = new Set(['read', 'grep', 'find', 'ls']);
const FILE_WRITE_BUILTINS = new Set(['edit', 'write']);
const MANAGED_RG_PATH_ENV = 'CINDY_PI_MANAGED_RG_PATH';

// Pi 的模型鉴权、localhost proxy 与 MCP bearer 需要留在父进程 env 供 runtime
// 按请求解析，但绝不能继承进 LLM 可调用的 bash 子进程。名单由 host 按本次会话
// 实际注入的动态 BYOM env 生成；permission file 同样隐藏，避免一次获批的 bash
// 通过改写权限档给后续工具永久提权。
const SECRET_ENV_NAMES = new Set<string>([
  'CINDY_PI_SECRET_ENV_NAMES',
  'CINDY_PI_PERMISSION_FILE',
  MANAGED_RG_PATH_ENV,
  'PI_CODING_AGENT_DIR',
]);
try {
  const names = JSON.parse(process.env.CINDY_PI_SECRET_ENV_NAMES ?? '[]');
  if (Array.isArray(names)) {
    for (const name of names) {
      if (typeof name === 'string' && name.length > 0) SECRET_ENV_NAMES.add(name);
    }
  }
} catch {
  // host 生成的配置若损坏，仍至少隐藏名单变量与 permission file；权限门继续 fail closed。
}

function withoutPiSecrets(env: Record<string, string | undefined>): Record<string, string | undefined> {
  const clean = { ...env };
  for (const name of SECRET_ENV_NAMES) delete clean[name];
  return clean;
}

function managedRipgrepPath(): string {
  const configured = process.env[MANAGED_RG_PATH_ENV];
  if (!configured || !path.isAbsolute(configured)) {
    throw new Error('Cindy managed ripgrep is unavailable');
  }
  return configured;
}

// 凭证/密钥路径特征由 maker-core 的单一来源生成。bridge 自包含、运行时不能 import，
// 但不再维护第二份手写名单，避免新增凭证目录时 Pi 静默漏拦。
const CREDENTIAL_PATH_PATTERNS = ${JSON.stringify(SENSITIVE_CREDENTIAL_PATH_PATTERN_SPECS)}
  .map(({ source, flags }) => new RegExp(source, flags));
const REVIEW_CREDENTIAL_PATH_PATTERNS = ${JSON.stringify(REVIEW_SENSITIVE_CREDENTIAL_PATH_PATTERN_SPECS)}
  .map(({ source, flags }) => new RegExp(source, flags));
const REVIEW_CREDENTIAL_GLOB_PATTERNS = ${JSON.stringify(REVIEW_SENSITIVE_CREDENTIAL_GLOB_PATTERNS)};

// 递归扫全部字符串叶子(含数组 / 嵌套对象),深度上限防环/超大入参。工具入参把路径
// 放进 { paths: [...] } 或 { opts: { path } } 时也能命中,不止顶层 string 字段。
function touchesCredentialPath(input: unknown, depth = 0): boolean {
  if (depth > 6 || input == null) return false;
  if (typeof input === 'string') return CREDENTIAL_PATH_PATTERNS.some((re) => re.test(input));
  if (Array.isArray(input)) return input.some((v) => touchesCredentialPath(v, depth + 1));
  if (typeof input === 'object') {
    return Object.values(input as Record<string, unknown>).some((v) => touchesCredentialPath(v, depth + 1));
  }
  return false;
}

// 未解析的路径字符串命不中凭证特征,但工作区内的符号链接可指向 /proc/self/environ 等
// 敏感目标;path.resolve 不跟随链接,故 touchesCredentialPath 会漏判(greptile 报)。这里
// 对每个字符串叶子额外 realpathSync 跟随链接,用**解析后**的真实目标再匹配一次特征。
// realpathSync 对不存在/非路径字符串会抛,catch 即跳过(仍有原始字符串检查兜底)。
function resolvesToCredentialPath(input: unknown, depth = 0): boolean {
  if (depth > 6 || input == null) return false;
  if (typeof input === 'string') {
    if (!input) return false;
    try {
      const resolved = realpathSync(input);
      return CREDENTIAL_PATH_PATTERNS.some((re) => re.test(resolved));
    } catch {
      return false;
    }
  }
  if (Array.isArray(input)) return input.some((v) => resolvesToCredentialPath(v, depth + 1));
  if (typeof input === 'object') {
    return Object.values(input as Record<string, unknown>).some((v) => resolvesToCredentialPath(v, depth + 1));
  }
  return false;
}

// 从 bash 子进程读取任意进程的初始环境(/proc/<pid|self>/environ)是绕过密钥剥离的旁路:
// spawn 边界虽从子进程 env 删了 Cindy 私密变量,但父 pi 进程仍持有它们,同 UID 下
// cat /proc/PPID/environ 可直接取回代理 token / 网关 key / BYOM key(codex 报)。
// 无法从 JS 侧让 /proc 不可读,故在工具边界对这类命令一律硬拦(含 Full access)。
// 线程视图 /proc/<pid>/task/<tid>/environ(乃至其它中间段)与 /proc/<pid>/environ 等价可读,
// 同样拦。中间段允许含斜杠(旧正则用 [^/...]* 只认单段,漏了 task/<tid>,codex report),
// 与 readonly-builtin 硬拦所用的共享 SENSITIVE_CREDENTIAL_PATH 特征(/proc/[^斜杠空白]*/environ)
// 保持同等覆盖。注:命令文本匹配不是安全边界(变形/间接读取可绕过,详见 pi-harness.md 的
// Full access 契约),这里只是 defense-in-depth。
// (本文件是 String.raw 模板,注释里严禁反引号,否则会提前终结模板。)
const PROC_ENVIRON_READ_RE = /\/proc\/[^\s'"]*\/environ\b/i;
function commandReadsProcessEnviron(command: unknown): boolean {
  return typeof command === 'string' && PROC_ENVIRON_READ_RE.test(command);
}

function currentPermissionState(): {
  mode: 'ask' | 'bypassPermissions';
  readOnlyRoots: string[];
  reviewReadPaths: string[];
  reviewOnly: boolean;
} {
  const file = process.env.CINDY_PI_PERMISSION_FILE ?? '';
  if (!file) return { mode: 'ask', readOnlyRoots: [], reviewReadPaths: [], reviewOnly: false };
  try {
    const parsed = JSON.parse(readFileSync(file, 'utf8'));
    return {
      mode: parsed?.mode === 'bypassPermissions' ? 'bypassPermissions' : 'ask',
      readOnlyRoots: Array.isArray(parsed?.readOnlyRoots)
        ? parsed.readOnlyRoots.filter((root: unknown) => typeof root === 'string')
        : [],
      reviewReadPaths: Array.isArray(parsed?.reviewReadPaths)
        ? parsed.reviewReadPaths.filter((root: unknown) => typeof root === 'string')
        : [],
      reviewOnly: parsed?.reviewOnly === true,
    };
  } catch {
    return { mode: 'ask', readOnlyRoots: [], reviewReadPaths: [], reviewOnly: false };
  }
}

function isInsideRoot(candidate: string, root: string): boolean {
  const target = path.resolve(candidate);
  const base = path.resolve(root);
  const rel = path.relative(base, target);
  return rel === '' || (!rel.startsWith('..' + path.sep) && rel !== '..' && !path.isAbsolute(rel));
}

function reviewAncestorsWithin(start: string, root: string): string[] {
  const boundary = path.resolve(root);
  const ancestors: string[] = [];
  let current = path.resolve(start);
  while (isInsideRoot(current, boundary)) {
    ancestors.push(current);
    if (current === boundary) break;
    const parent = path.dirname(current);
    if (parent === current) break;
    current = parent;
  }
  return ancestors;
}

function reviewStatsReferToSameFile(
  left: ReturnType<typeof statSync>,
  right: ReturnType<typeof statSync>,
): boolean {
  return left.ino !== 0 && left.dev === right.dev && left.ino === right.ino;
}

const REVIEW_PACKAGE_MANIFEST_MAX_BYTES = 256 * 1024;

function normalizeReviewDeclaredPackageName(value: unknown): string | null {
  if (
    typeof value !== 'string'
    || value.length === 0
    || value.length > 214
    || value !== value.trim()
  ) return null;
  const component = '[a-z0-9][a-z0-9._-]*';
  const pattern = value.startsWith('@')
    ? new RegExp('^@' + component + '/' + component + '$', 'i')
    : new RegExp('^' + component + '$', 'i');
  return pattern.test(value) ? value : null;
}

function reviewDeclaredPackageName(
  packageRoot: string,
  confinementRoot: string,
): string | null {
  try {
    const manifestPath = path.join(packageRoot, 'package.json');
    if (!isInsideRoot(manifestPath, confinementRoot)) return null;
    const manifestLstat = lstatSync(manifestPath);
    if (
      manifestLstat.isSymbolicLink()
      || !manifestLstat.isFile()
      || manifestLstat.size > REVIEW_PACKAGE_MANIFEST_MAX_BYTES
    ) return null;
    const realManifest = realpathSync(manifestPath);
    if (!isInsideRoot(realManifest, confinementRoot)) return null;
    const manifestStat = statSync(realManifest);
    if (!manifestStat.isFile() || manifestStat.size > REVIEW_PACKAGE_MANIFEST_MAX_BYTES) {
      return null;
    }
    const raw = readFileSync(realManifest, 'utf8');
    if (Buffer.byteLength(raw, 'utf8') > REVIEW_PACKAGE_MANIFEST_MAX_BYTES) return null;
    return normalizeReviewDeclaredPackageName(JSON.parse(raw)?.name);
  } catch {
    return null;
  }
}

function reviewFileLinkLayoutIsSafe(
  target: string,
  targetStat: ReturnType<typeof statSync>,
  confinementRoot: string,
): boolean {
  if (!targetStat.isFile()) return targetStat.isDirectory();
  if (targetStat.nlink <= 1) return true;
  if (targetStat.nlink !== 2 || !isInsideRoot(target, confinementRoot)) {
    return false;
  }
  const candidates = new Set<string>();
  for (const packageRoot of reviewAncestorsWithin(path.dirname(target), confinementRoot)) {
    const packageBase = path.basename(packageRoot);
    if (!packageBase || packageBase === path.sep || packageBase === 'node_modules') continue;
    const packageNames = [packageBase];
    const declaredPackageName = reviewDeclaredPackageName(packageRoot, confinementRoot);
    if (declaredPackageName) packageNames.push(declaredPackageName);
    const scope = path.basename(path.dirname(packageRoot));
    if (scope.startsWith('@') && scope.length > 1) {
      packageNames.push(path.join(scope, packageBase));
    }
    const relativePath = path.relative(packageRoot, target);
    if (!relativePath || relativePath.startsWith('..' + path.sep) || path.isAbsolute(relativePath)) {
      continue;
    }
    for (const dependencyRoot of reviewAncestorsWithin(path.dirname(packageRoot), confinementRoot)) {
      for (const packageName of packageNames) {
        candidates.add(path.join(dependencyRoot, 'node_modules', packageName, relativePath));
      }
    }
  }
  for (const candidate of candidates) {
    if (!REVIEW_CREDENTIAL_PATH_PATTERNS.some((re) => re.test(candidate))) continue;
    try {
      const candidateStat = lstatSync(candidate);
      if (
        candidateStat.isSymbolicLink()
        || !candidateStat.isFile()
        || candidateStat.nlink !== 2
        || !reviewStatsReferToSameFile(targetStat, candidateStat)
      ) {
        continue;
      }
      const realCandidate = realpathSync(candidate);
      if (
        path.resolve(realCandidate) !== path.resolve(target)
        && isInsideRoot(realCandidate, confinementRoot)
        && REVIEW_CREDENTIAL_PATH_PATTERNS.some((re) => re.test(realCandidate))
      ) {
        return true;
      }
    } catch {
      // Candidate disappeared or changed while validating; fail closed below.
    }
  }
  return false;
}

function resolveReviewReadPath(candidate: string, allowedPaths: string[]): string | null {
  try {
    const requested = path.resolve(process.cwd(), candidate);
    if (REVIEW_CREDENTIAL_PATH_PATTERNS.some((re) => re.test(requested))) return null;
    const target = realpathSync(requested);
    if (REVIEW_CREDENTIAL_PATH_PATTERNS.some((re) => re.test(target))) return null;
    const targetStat = statSync(target);
    const allowed = allowedPaths.some((allowedPath) => {
      try {
        const allowed = realpathSync(allowedPath);
        const stat = statSync(allowed);
        if (stat.isFile() && stat.nlink > 1) return false;
        if (stat.isDirectory()) {
          return (
            isInsideRoot(target, allowed)
            && reviewFileLinkLayoutIsSafe(target, targetStat, allowed)
          );
        }
        return targetStat.nlink <= 1 && target === allowed;
      } catch {
        return false;
      }
    });
    return allowed ? target : null;
  } catch {
    return null;
  }
}

const REVIEW_PATH_FIELD_KEYS = new Set([
  'path',
  'paths',
  'file_path',
  'filepath',
  'notebook_path',
  'notebookpath',
]);

type ReviewPathField = {
  candidate: string;
  write: (resolved: string) => void;
};

// Read tools have changed their input nesting across Pi versions. Walk every
// object branch, retain a writer for every path-bearing field, then replace all
// fields with the exact real paths that passed validation. Invalid or over-deep
// path shapes fail closed without reaching the built-in tool.
function collectReviewPathFields(input: unknown): ReviewPathField[] | null {
  if (
    input == null
    || typeof input !== 'object'
    || Array.isArray(input)
  ) return null;
  const fields: ReviewPathField[] = [];
  const visit = (
    value: unknown,
    field: string | null,
    depth: number,
    write: (resolved: string) => void,
  ): boolean => {
    if (depth > 6) return false;
    const normalizedField = field?.toLowerCase() ?? null;
    if (normalizedField && REVIEW_PATH_FIELD_KEYS.has(normalizedField)) {
      const plural = normalizedField === 'paths';
      if (plural) {
        if (!Array.isArray(value)) return false;
        for (let index = 0; index < value.length; index += 1) {
          const item = value[index];
          if (typeof item !== 'string') return false;
          fields.push({
            candidate: item || process.cwd(),
            write: (resolved) => { value[index] = resolved; },
          });
        }
        return true;
      }
      if (typeof value !== 'string') return false;
      fields.push({ candidate: value || process.cwd(), write });
      return true;
    }
    if (value == null) return true;
    if (Array.isArray(value)) {
      return value.every((item, index) =>
        visit(item, null, depth + 1, (resolved) => { value[index] = resolved; }));
    }
    if (typeof value === 'object') {
      const record = value as Record<string, unknown>;
      return Object.entries(record)
        .every(([key, child]) =>
          visit(child, key, depth + 1, (resolved) => { record[key] = resolved; }));
    }
    return true;
  };
  return visit(input, null, 0, () => {}) ? fields : null;
}

function reviewSelectorEscapesScope(selector: string): boolean {
  const value = selector.trim();
  if (!value) return false;
  if (path.isAbsolute(value) || path.win32.isAbsolute(value)) return true;
  if (/[\\[\]]/.test(value) || value.includes('..')) return true;
  return /(^|[{(,|])(?:\/|[a-zA-Z]:\/)/.test(value);
}

function reviewSelectorTouchesCredential(selector: string): boolean {
  const candidates = [selector, ...selector.split(/[{},|]/)];
  return candidates.some((candidate) => {
    if (REVIEW_CREDENTIAL_PATH_PATTERNS.some((re) => re.test(candidate))) return true;
    const literalized = candidate.replace(/[*?[\]{}()!+@]/g, '');
    return literalized !== candidate
      && REVIEW_CREDENTIAL_PATH_PATTERNS.some((re) => re.test(literalized));
  });
}

function collectReviewFileSelectors(toolName: string, input: unknown): string[] | null {
  if (toolName !== 'grep' && toolName !== 'find') return [];
  const selectorFields = toolName === 'grep'
    ? new Set(['glob', 'globs'])
    : new Set(['glob', 'globs', 'pattern', 'patterns']);
  const selectors: string[] = [];
  const visit = (value: unknown, field: string | null, depth: number): boolean => {
    if (depth > 6) return false;
    const normalizedField = field?.toLowerCase() ?? null;
    if (normalizedField && selectorFields.has(normalizedField)) {
      if (Array.isArray(value)) {
        for (const item of value) {
          if (typeof item !== 'string') return false;
          selectors.push(item);
        }
        return true;
      }
      if (typeof value !== 'string') return false;
      selectors.push(value);
      return true;
    }
    if (value == null) return true;
    if (Array.isArray(value)) {
      return value.every((item) => visit(item, null, depth + 1));
    }
    if (typeof value === 'object') {
      return Object.entries(value as Record<string, unknown>)
        .every(([key, child]) => visit(child, key, depth + 1));
    }
    return true;
  };
  return visit(input, null, 0) ? selectors : null;
}

function normalizeReviewReadInput(
  toolName: string,
  input: unknown,
  allowedPaths: string[],
): boolean {
  const pathFields = collectReviewPathFields(input);
  const selectors = collectReviewFileSelectors(toolName, input);
  if (!pathFields || !selectors) return false;
  if (selectors.some((selector) =>
    reviewSelectorEscapesScope(selector) || reviewSelectorTouchesCredential(selector))) {
    return false;
  }
  const requestedPaths = pathFields.length > 0
    ? pathFields.map((field) => field.candidate)
    : [process.cwd()];
  const resolvedPaths = requestedPaths.map((candidate) =>
    resolveReviewReadPath(candidate, allowedPaths));
  if (resolvedPaths.some((resolved) => resolved === null)) return false;
  if (pathFields.length === 0) {
    (input as Record<string, unknown>).path = resolvedPaths[0]!;
  } else {
    for (let index = 0; index < pathFields.length; index += 1) {
      pathFields[index].write(resolvedPaths[index]!);
    }
  }
  return true;
}

function reviewSearchPathTouchesCredential(candidate: string, baseDir = process.cwd()): boolean {
  const requested = path.resolve(baseDir, candidate);
  const normalized = requested.split(path.sep).join('/');
  if (REVIEW_CREDENTIAL_PATH_PATTERNS.some((re) => re.test(requested))) return true;
  try {
    return REVIEW_CREDENTIAL_GLOB_PATTERNS.some((pattern) =>
      path.matchesGlob(normalized, pattern));
  } catch {
    return true;
  }
}

function reviewSearchPathHasUnsafeLinkLayout(
  candidate: string,
  allowedPaths: string[],
  baseDir = process.cwd(),
): boolean {
  try {
    const requested = path.resolve(baseDir, candidate);
    const target = realpathSync(requested);
    const targetStat = statSync(target);
    if (!targetStat.isFile() || targetStat.nlink <= 1) return false;
    const safeWithinGrant = allowedPaths.some((allowedPath) => {
      try {
        const allowed = realpathSync(allowedPath);
        const allowedStat = statSync(allowed);
        return (
          allowedStat.isDirectory()
          && isInsideRoot(target, allowed)
          && reviewFileLinkLayoutIsSafe(target, targetStat, allowed)
        );
      } catch {
        return false;
      }
    });
    if (!safeWithinGrant) return true;
    const finalTarget = realpathSync(requested);
    const finalStat = statSync(finalTarget);
    return (
      path.resolve(finalTarget) !== path.resolve(target)
      || !reviewStatsReferToSameFile(targetStat, finalStat)
      || finalStat.nlink !== targetStat.nlink
    );
  } catch {
    return true;
  }
}

function reviewSearchPathIsVisible(
  candidate: string,
  allowedPaths: string[],
  baseDir = process.cwd(),
): boolean {
  return (
    !reviewSearchPathTouchesCredential(candidate, baseDir)
    && !reviewSearchPathHasUnsafeLinkLayout(candidate, allowedPaths, baseDir)
  );
}

function reviewGrepOutputPath(line: string): string | null {
  const match = /^(.*?)(?::\d+:|-\d+-)/.exec(line);
  return match?.[1] ?? null;
}

function filterReviewGrepResult(result: any, input: unknown, allowedPaths: string[]): any {
  if (!result || typeof result !== 'object' || !Array.isArray(result.content)) {
    return { content: [{ type: 'text', text: 'No matches found' }], details: undefined };
  }
  const record = input && typeof input === 'object' && !Array.isArray(input)
    ? input as Record<string, unknown>
    : {};
  const requestedPath = typeof record.path === 'string' && record.path ? record.path : '.';
  const searchTarget = path.resolve(process.cwd(), requestedPath);
  let resultBase = process.cwd();
  try {
    resultBase = statSync(searchTarget).isDirectory() ? searchTarget : path.dirname(searchTarget);
  } catch {
    return { content: [{ type: 'text', text: 'No matches found' }], details: undefined };
  }

  let visibleMatch = false;
  const content = result.content.map((item: any) => {
    if (!item || typeof item !== 'object' || typeof item.text !== 'string') return item;
    const lines = item.text.split('\n').filter((line: string) => {
      const candidate = reviewGrepOutputPath(line);
      if (!candidate) return true;
      if (!reviewSearchPathIsVisible(candidate, allowedPaths, resultBase)) return false;
      visibleMatch = true;
      return true;
    });
    return { ...item, text: lines.join('\n') };
  });
  return visibleMatch
    ? { ...result, content }
    : { content: [{ type: 'text', text: 'No matches found' }], details: undefined };
}

// ── MCP streamable-HTTP 极简 client ─────────────────────────────────────────

interface McpServerRef {
  name: string;
  url: string;
  remote?: {
    headerEnvVars: Record<string, string>;
    startupTimeoutMs: number;
    requestTimeoutMs: number;
  };
}

class McpBridgeError extends Error {}

function safeMcpFailure(error: unknown): string {
  return error instanceof McpBridgeError ? error.message : 'unexpected error';
}

function isLoopbackMcpHostname(hostname: string): boolean {
  const normalized = hostname.toLowerCase();
  return normalized === 'localhost'
    || normalized === '127.0.0.1'
    || normalized === '::1'
    || normalized === '[::1]';
}

function isAllowedMcpUrl(url: URL): boolean {
  if (url.username || url.password) return false;
  if (url.protocol === 'https:') return true;
  return url.protocol === 'http:' && isLoopbackMcpHostname(url.hostname);
}

class McpHttpClient {
  private nextId = 1;
  private sessionId: string | null = null;
  private readonly requestUrl: string;
  private readonly requestTimeoutMs: number;
  private startupDeadlineAt: number | null;

  constructor(
    private readonly server: McpServerRef,
    private readonly token: string,
  ) {
    let parsed: URL;
    try {
      parsed = new URL(server.url);
    } catch {
      throw new McpBridgeError('invalid URL');
    }
    // 外部 URL 的 host 边界由用户保存的 endpoint 决定；这里再做 web-only fail-closed，
    // 防描述符损坏后把 Pi 变成 file/data 等协议读取器。非 loopback 必须 HTTPS；URL
    // 内嵌凭证也禁止，避免它们进入 bridge JSON，认证必须走专用 env。
    if (!isAllowedMcpUrl(parsed)) {
      throw new McpBridgeError('URL outside security boundary');
    }
    this.requestUrl = parsed.href;
    const configuredTimeout = server.remote?.requestTimeoutMs;
    this.requestTimeoutMs = Number.isInteger(configuredTimeout)
      && configuredTimeout! > 0
      && configuredTimeout! <= 600_000
      ? configuredTimeout!
      : 600_000;
    const configuredStartupTimeout = server.remote?.startupTimeoutMs;
    const startupTimeoutMs = Number.isInteger(configuredStartupTimeout)
      && configuredStartupTimeout! > 0
      && configuredStartupTimeout! < 30_000
      ? configuredStartupTimeout!
      : 10_000;
    this.startupDeadlineAt = Date.now() + startupTimeoutMs;
  }

  private nextRequestTimeoutMs(): number {
    if (this.startupDeadlineAt === null) return this.requestTimeoutMs;
    const remaining = this.startupDeadlineAt - Date.now();
    if (remaining <= 0) throw new McpBridgeError('startup timed out');
    return Math.max(1, Math.min(this.requestTimeoutMs, remaining));
  }

  finishStartup(): void {
    this.startupDeadlineAt = null;
  }

  private headers(): Headers {
    const h = new Headers();
    try {
      if (this.server.remote) {
        for (const [headerName, envName] of Object.entries(this.server.remote.headerEnvVars ?? {})) {
          if (typeof envName !== 'string' || !envName) {
            throw new McpBridgeError('invalid authentication configuration');
          }
          const value = process.env[envName];
          if (value === undefined) throw new McpBridgeError('missing authentication environment');
          h.set(headerName, value);
        }
      } else {
        if (!this.token) throw new McpBridgeError('missing local bridge token');
        h.set('authorization', 'Bearer ' + this.token);
      }
      // 协议 header 与 server 颁发的 session id 由 client 掌控，不能被自定义 header 覆盖。
      h.set('content-type', 'application/json');
      h.set('accept', 'application/json, text/event-stream');
      h.delete('mcp-session-id');
      if (this.sessionId) h.set('mcp-session-id', this.sessionId);
    } catch (error) {
      if (error instanceof McpBridgeError) throw error;
      throw new McpBridgeError('invalid authentication header');
    }
    return h;
  }

  private async post<T>(body: unknown, consume: (response: Response) => Promise<T>): Promise<T> {
    const requestTimeoutMs = this.nextRequestTimeoutMs();
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), requestTimeoutMs);
    try {
      const res = await fetch(this.requestUrl, {
        method: 'POST',
        headers: this.headers(),
        body: JSON.stringify(body),
        redirect: 'error',
        signal: controller.signal,
      });
      const sid = res.headers.get('mcp-session-id');
      if (sid) this.sessionId = sid;
      // consume 在同一个 AbortController 生命周期内完成，故 200/SSE 响应头后卡住的
      // body 也会按 requestTimeoutMs 中止，不会无限阻塞后续 server 注册。
      return await consume(res);
    } catch (error) {
      if (controller.signal.aborted) throw new McpBridgeError('request timed out');
      if (error instanceof McpBridgeError) throw error;
      if (error instanceof SyntaxError) throw new McpBridgeError('invalid JSON response');
      throw new McpBridgeError('request failed');
    } finally {
      clearTimeout(timeout);
    }
  }

  /** 按 SSE event 增量取当前 JSON-RPC response；server 保持流打开也不阻塞。 */
  private async readSseResponse(res: Response, id: number): Promise<any> {
    const reader = res.body?.getReader();
    if (!reader) throw new McpBridgeError('invalid SSE response');
    const decoder = new TextDecoder();
    let buffered = '';
    const parseEvent = (eventText: string): any | null => {
      const data = eventText
        .split(/\r\n|\r|\n/)
        .filter((line) => line.startsWith('data:'))
        .map((line) => {
          const value = line.slice(5);
          return value.startsWith(' ') ? value.slice(1) : value;
        })
        .join('\n');
      if (!data) return null;
      try {
        const msg = JSON.parse(data);
        if (msg && msg.id === id && ('result' in msg || 'error' in msg)) return msg;
      } catch {
        // 其它 event / 非 JSON data 不属于当前 response，继续读流。
      }
      return null;
    };

    try {
      for (;;) {
        const { done, value } = await reader.read();
        if (value) buffered += decoder.decode(value, { stream: true });
        if (done) buffered += decoder.decode();

        for (;;) {
          const boundary = /\r\n\r\n|\n\n|\r\r/.exec(buffered);
          if (!boundary) break;
          const eventText = buffered.slice(0, boundary.index);
          buffered = buffered.slice(boundary.index + boundary[0].length);
          const msg = parseEvent(eventText);
          if (msg) return msg;
        }
        if (buffered.length > 1_048_576) {
          throw new McpBridgeError('invalid SSE response');
        }
        if (done) {
          const msg = parseEvent(buffered);
          if (msg) return msg;
          throw new McpBridgeError('invalid SSE response');
        }
      }
    } finally {
      // 找到当前 response 后不等待 server 关闭持续流，立即释放连接。
      void reader.cancel().catch(() => {});
    }
  }

  /** 解析 application/json 或 SSE 响应体里 id 匹配的 JSON-RPC response。 */
  private async readResponse(res: Response, id: number): Promise<any> {
    const contentType = res.headers.get('content-type') ?? '';
    if (!res.ok) {
      // 远端错误体可能回显 Authorization / API key，绝不拼进 Pi stderr。
      void res.body?.cancel().catch(() => {});
      throw new McpBridgeError('HTTP ' + res.status);
    }
    if (contentType.includes('text/event-stream')) {
      return this.readSseResponse(res, id);
    }
    return res.json();
  }

  async request(method: string, params?: unknown): Promise<any> {
    const id = this.nextId++;
    const msg = await this.post(
      { jsonrpc: '2.0', id, method, ...(params !== undefined ? { params } : {}) },
      (res) => this.readResponse(res, id),
    );
    if (msg.error) {
      throw new McpBridgeError('MCP ' + method + ' returned an error');
    }
    return msg.result;
  }

  async notify(method: string, params?: unknown): Promise<void> {
    await this.post(
      { jsonrpc: '2.0', method, ...(params !== undefined ? { params } : {}) },
      async (res) => { await res.body?.cancel(); },
    ).catch(() => {});
  }

  async initialize(): Promise<void> {
    await this.request('initialize', {
      protocolVersion: '2025-03-26',
      capabilities: {},
      clientInfo: { name: 'cindy-pi-bridge', version: '1.0.0' },
    });
    await this.notify('notifications/initialized');
  }
}

function mcpContentToPi(content: unknown): Array<Record<string, unknown>> {
  const out: Array<Record<string, unknown>> = [];
  if (Array.isArray(content)) {
    for (const item of content) {
      if (!item || typeof item !== 'object') continue;
      const rec = item as Record<string, unknown>;
      if (rec.type === 'text' && typeof rec.text === 'string') {
        out.push({ type: 'text', text: rec.text });
      } else if (rec.type === 'image' && typeof rec.data === 'string') {
        out.push({ type: 'image', data: rec.data, mimeType: rec.mimeType ?? 'image/png' });
      } else {
        out.push({ type: 'text', text: JSON.stringify(rec) });
      }
    }
  }
  if (out.length === 0) out.push({ type: 'text', text: '(empty result)' });
  return out;
}

async function connectServer(pi: any, server: McpServerRef, token: string): Promise<number> {
  const client = new McpHttpClient(server, token);
  await client.initialize();
  const tools: any[] = [];
  const seenCursors = new Set<string>();
  let cursor: string | undefined;
  for (;;) {
    const listed = await client.request('tools/list', cursor === undefined ? {} : { cursor });
    if (Array.isArray(listed?.tools)) tools.push(...listed.tools);
    if (!listed || typeof listed !== 'object' || !('nextCursor' in listed)) break;
    const nextCursor = listed.nextCursor;
    if (typeof nextCursor !== 'string' || seenCursors.has(nextCursor)) {
      throw new McpBridgeError('invalid tools pagination');
    }
    seenCursors.add(nextCursor);
    cursor = nextCursor;
  }
  client.finishStartup();
  for (const tool of tools) {
    const qualifiedName = 'mcp__' + server.name + '__' + tool.name;
    const parameters =
      tool.inputSchema && typeof tool.inputSchema === 'object'
        ? tool.inputSchema
        : { type: 'object', properties: {}, additionalProperties: true };
    try {
      pi.registerTool({
        name: qualifiedName,
        label: server.name + ': ' + tool.name,
        description: typeof tool.description === 'string' && tool.description.length > 0
          ? tool.description
          : 'MCP tool ' + tool.name + ' from ' + server.name,
        parameters,
        async execute(_toolCallId: string, params: unknown) {
          const result = await client.request('tools/call', {
            name: tool.name,
            arguments: params ?? {},
          });
          const content = mcpContentToPi(result?.content);
          if (result?.isError) {
            const text = content
              .map((c) => (typeof c.text === 'string' ? c.text : ''))
              .join('\n')
              .trim();
            throw new Error(text.length > 0 ? text : 'MCP tool ' + tool.name + ' failed');
          }
          return { content, details: result?.structuredContent ?? {} };
        },
      });
    } catch (err) {
      console.error('[cindy-bridge] register ' + qualifiedName + ' failed: ' + String(err));
    }
  }
  return tools.length;
}

// Pi 内置 find 依赖 fd；PI_OFFLINE=1 时缺失后不会下载。Cindy 已随 Desktop 校验并
// 提供 rg，因此把固定参数的 rg --files 适配成 Pi 原生 find operations。参数直接传
// spawn、不经 shell；文件模式在 JS 里过滤，因为 rg 的 positive glob 会覆盖 .gitignore。
function rgGlob(
  pattern: string,
  cwd: string,
  options: { ignore: string[]; limit: number },
): Promise<string[]> {
  return new Promise((resolve, reject) => {
    const permission = currentPermissionState();
    const reviewOnly = permission.reviewOnly;
    const limit = Number.isFinite(options.limit) ? Math.max(1, Math.floor(options.limit)) : 1000;
    const args = ['--files', '--hidden', '--no-require-git'];
    for (const ignored of options.ignore) args.push('--glob', '!' + ignored);

    const child = spawn(managedRipgrepPath(), args, {
      cwd,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    const lines: string[] = [];
    let stderr = '';
    let stoppedAtLimit = false;
    let settled = false;
    const settle = (fn: () => void) => {
      if (settled) return;
      settled = true;
      fn();
    };
    const reader = createInterface({ input: child.stdout });
    reader.on('line', (line) => {
      if (!line || lines.length >= limit) return;
      const relative = line.replace(/\r$/, '');
      if (reviewOnly && !reviewSearchPathIsVisible(relative, permission.reviewReadPaths, cwd)) return;
      // 完整镜像 Pi 上游 fd 规则：无 slash 时匹配 basename；有 slash 时启用
      // full-path，且相对 pattern 自动加 **/，让 src/** 同时命中 monorepo 子包。
      let candidate = path.basename(relative);
      let effectivePattern = pattern;
      if (pattern.includes('/')) {
        candidate = path.resolve(cwd, relative).split(path.sep).join('/');
        if (!pattern.startsWith('/') && !pattern.startsWith('**/') && pattern !== '**') {
          effectivePattern = '**/' + pattern;
        }
      }
      // path.matchesGlob 默认不让 * 匹配点开头的段；rg glob 会匹配。保留原路径先匹配
      // 显式点模式，再用等长占位符补齐 --hidden 下的普通通配语义。
      const visibleCandidate = candidate.replace(/(^|[\\/])\./g, '$1_');
      if (!path.matchesGlob(candidate, effectivePattern)
        && !path.matchesGlob(visibleCandidate, effectivePattern)) return;
      lines.push(path.join(cwd, relative));
      if (lines.length >= limit && !child.killed) {
        stoppedAtLimit = true;
        child.kill();
      }
    });
    child.stderr.on('data', (chunk) => { stderr += chunk.toString(); });
    child.on('error', (error) => {
      reader.close();
      settle(() => reject(new Error('Failed to run Cindy ripgrep: ' + error.message)));
    });
    child.on('close', (code) => {
      reader.close();
      if (!stoppedAtLimit && code !== 0 && code !== 1) {
        const message = stderr.trim() || 'ripgrep exited with code ' + String(code);
        settle(() => reject(new Error(message)));
        return;
      }
      settle(() => resolve(lines));
    });
  });
}

export default async function cindyBridge(pi: any) {
  // 主 Pi 不传 --tools：那个白名单也会筛掉动态 MCP 与 subagent。改由 bridge 注册
  // 专用只读工具；子代理仍用自己的 read,grep,find,ls 白名单收紧能力面。
  const grepTool = createGrepTool(process.cwd());
  pi.registerTool({
    ...grepTool,
    execute: async (id: string, params: unknown, signal: AbortSignal, onUpdate: unknown) => {
      // Fail closed before Pi upstream ensureTool can fall back to cwd/PATH lookup.
      managedRipgrepPath();
      const permission = currentPermissionState();
      const result = await grepTool.execute(id, params as any, signal, onUpdate as any);
      return permission.reviewOnly
        ? filterReviewGrepResult(result, params, permission.reviewReadPaths)
        : result;
    },
  });

  // 覆盖内置 find：保留 Pi 原生 schema、渲染、截断和权限工具名，只替换文件枚举后端。
  const findTool = createFindTool(process.cwd(), {
    operations: {
      exists: async (candidate: string) => {
        try {
          await stat(candidate);
          return true;
        } catch {
          return false;
        }
      },
      glob: rgGlob,
    },
  });
  pi.registerTool({
    ...findTool,
    execute: async (id: string, params: unknown, signal: AbortSignal, onUpdate: unknown) =>
      findTool.execute(id, params as any, signal, onUpdate as any),
  });

  const lsTool = createLsTool(process.cwd());
  pi.registerTool({
    ...lsTool,
    execute: async (id: string, params: unknown, signal: AbortSignal, onUpdate: unknown) =>
      lsTool.execute(id, params as any, signal, onUpdate as any),
  });

  // 覆盖内置 bash：保持 Pi 原生执行/截断/取消语义，只在 spawn 边界剥离 Cindy
  // 私密变量。模型仍可正常发请求，但它执行的任意命令拿不到 proxy/MCP/BYOM 凭证。
  const bashTool = createBashTool(process.cwd(), {
    // PI_SESSION_FILE 会暴露 agentHome，继而让一次获批的 shell 定位并篡改
    // permission file；其余 PI_SESSION_* 元数据对完成编码任务也不是必需能力。
    exposeSessionEnvironment: false,
    spawnHook: ({ command, cwd, env }) => ({
      command,
      cwd,
      env: withoutPiSecrets(env),
    }),
  });
  pi.registerTool({
    ...bashTool,
    execute: async (id: string, params: unknown, signal: AbortSignal, onUpdate: unknown) =>
      bashTool.execute(id, params as any, signal, onUpdate as any),
  });

  // ── 原生会话树桥 ──────────────────────────────────────────────────────────
  // RPC 没有 navigate_tree command；ExtensionCommandContext 才暴露 navigateTree。
  // 参数用 percent-encoded JSON，避免 prompt 命令的空格/斜杠解析污染 payload。
  pi.registerCommand('cindy-branch-switch', {
    description: 'Cindy internal session branch navigation',
    handler: async (args: string, ctx: any) => {
      let payload: {
        entryId?: unknown;
        summarize?: unknown;
        customInstructions?: unknown;
        label?: unknown;
      };
      try {
        payload = JSON.parse(decodeURIComponent(args.trim()));
      } catch {
        throw new Error('Invalid Cindy branch payload');
      }
      if (typeof payload.entryId !== 'string' || payload.entryId.length === 0 || payload.entryId.length > 128) {
        throw new Error('Invalid Cindy branch entry id');
      }
      const customInstructions = typeof payload.customInstructions === 'string'
        ? payload.customInstructions.trim().slice(0, 4000)
        : undefined;
      const label = typeof payload.label === 'string'
        ? payload.label.trim().slice(0, 120)
        : undefined;
      await ctx.waitForIdle();
      await ctx.navigateTree(payload.entryId, {
        summarize: payload.summarize === true,
        ...(customInstructions ? { customInstructions } : {}),
        ...(label ? { label } : {}),
      });
    },
  });

  // ── 权限门 ────────────────────────────────────────────────────────────────
  pi.on('tool_call', async (event: any, ctx: any) => {
    const permission = currentPermissionState();
    if (permission.reviewOnly) {
      if (
        READONLY_BUILTINS.has(event.toolName)
        && normalizeReviewReadInput(
          event.toolName,
          event.input,
          permission.reviewReadPaths,
        )
      ) return;
      return {
        block: true,
        reason: 'Cindy Review only permits read-only access to this task and its explicit artifacts.',
      };
    }
    if (FILE_WRITE_BUILTINS.has(event.toolName)) {
      try {
        // Internal synchronization point: the host snapshots only the target file for
        // known-path writes. The result is deliberately ignored; capture must never turn
        // an observability failure into a tool-execution failure.
        await ctx.ui.confirm(
          TURN_CHANGE_CAPTURE_TITLE,
          JSON.stringify({
            toolName: event.toolName,
            toolUseId: event.toolCallId,
            input: event.input ?? {},
          }),
        );
      } catch {
        // Best-effort capture; the permission boundary below remains authoritative.
      }
    }
    // Extra Dirs 的结构化写工具永远禁止，即使 Full access 也不能把“只读引用”静默
    // 升级成写目录。bash 仍由 Cindy 审批/模型指令约束（Pi 暂无 OS sandbox API）。
    const targetPath = typeof event.input?.path === 'string' ? event.input.path : '';
    if (
      targetPath
      && FILE_WRITE_BUILTINS.has(event.toolName)
      && permission.readOnlyRoots.some((root) => isInsideRoot(targetPath, root))
    ) {
      return { block: true, reason: 'Cindy extra reference directories are read-only.' };
    }
    // bash 读取任意进程的初始环境(/proc/<pid|self>/environ)是绕过密钥剥离的旁路:
    // spawn 边界虽删了子进程 env 的私密变量,父 pi 进程仍持有,cat /proc/PPID/environ
    // 同 UID 直取代理 token / 网关 / BYOM key(codex 报)→ 一律硬拦,含 Full access。
    if (event.toolName === 'bash' && commandReadsProcessEnviron(event.input?.command)) {
      return { block: true, reason: 'Cindy blocks reading process environment (/proc/*/environ), even with Full access.' };
    }
    // 凭证/密钥路径的内置只读工具(read/grep/find/ls)在 Pi 父进程内执行,而父进程 env
    // 必须保留代理会话 token 与 BYOM keys($ENV 请求期解析、bridge client 使用)。Full
    // access 若放行 read /proc/self/environ 这类路径,模型可直接取 token 调回环代理,
    // 绕过审批盗刷当前会话额度(greptile 报)→ 即使 bypassPermissions 也硬拦。原始路径
    // 命不中时还要跟随符号链接:工作区内的 link 可指向敏感目标,realpath 后再判一次。
    const credentialRead = READONLY_BUILTINS.has(event.toolName)
      && (touchesCredentialPath(event.input) || resolvesToCredentialPath(event.input));
    if (credentialRead && permission.mode === 'bypassPermissions') {
      return { block: true, reason: 'Cindy blocks reading credential or key paths, even with Full access.' };
    }
    if (permission.mode === 'bypassPermissions') return;
    if (READONLY_BUILTINS.has(event.toolName) && !credentialRead) return;
    let approved = false;
    try {
      approved = await ctx.ui.confirm(
        PERMISSION_TITLE,
        JSON.stringify({ toolName: event.toolName, input: event.input ?? {} }),
      );
    } catch {
      approved = false;
    }
    if (!approved) {
      return { block: true, reason: 'User denied this tool call via Cindy.' };
    }
  });

  pi.on('tool_result', async (event: any, ctx: any) => {
    if (event.toolName !== 'bash' && !String(event.toolName ?? '').startsWith('mcp__')) return;
    try {
      await ctx.ui.confirm(
        TURN_CHANGE_CAPTURE_TITLE,
        JSON.stringify({
          toolName: event.toolName,
          toolUseId: event.toolCallId,
          input: event.input ?? {},
        }),
      );
    } catch {
      // Best-effort capture; tool results must never fail because observability did.
    }
  });

  // ── MCP 桥 ────────────────────────────────────────────────────────────────
  const raw = process.env.CINDY_PI_MCP_BRIDGE;
  if (!raw) return;
  let cfg: { token?: string; servers?: McpServerRef[] };
  try {
    cfg = JSON.parse(raw);
  } catch {
    console.error('[cindy-bridge] invalid CINDY_PI_MCP_BRIDGE JSON');
    return;
  }
  const token = cfg.token ?? '';
  // 全部 server 并行启动：每个 remote 有独立短预算，多个黑洞 provider 也只占一份
  // startup window，不会串行叠加到 Pi RPC 的 30s ready 超时。
  await Promise.all((cfg.servers ?? []).map(async (server) => {
    try {
      const count = await connectServer(pi, server, token);
      console.error('[cindy-bridge] connected ' + server.name + ' (' + count + ' tools)');
    } catch (err) {
      console.error('[cindy-bridge] connect ' + server.name + ' failed: ' + safeMcpFailure(err));
    }
  }));
}
`;
