/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/infra/errors.ts
/**
 * Error formatting helpers re-exported for Browser infrastructure modules.
 */
export { extractErrorCode, formatErrorMessage } from "../sdk-security-runtime.js";
