/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/infra/ports.ts
/**
 * Port availability helper re-exported for Browser startup checks.
 */
export { ensurePortAvailable } from "../sdk-security-runtime.js";
