/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/infra/tmp-openclaw-dir.ts
/**
 * Preferred OpenClaw temp directory helper for Browser outputs.
 */
export { resolvePreferredOpenClawTmpDir } from "../../../../shim/temp-path.js";
