/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/infra/net/proxy-env.ts
/**
 * Proxy environment detection re-exported for Browser network checks.
 */
export { hasProxyEnvConfigured } from "../../sdk-security-runtime.js";
