/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/infra/net/ssrf.ts
/**
 * SSRF policy helpers re-exported for Browser network/navigation guards.
 */
export {
  SsrFBlockedError,
  isPrivateNetworkAllowedByPolicy,
  resolvePinnedHostnameWithPolicy,
  type LookupFn,
  type SsrFPolicy,
} from "../../sdk-security-runtime.js";
