/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/utils/boolean.ts
/**
 * Boolean parsing helper re-exported for Browser CLI/config code.
 */
export { parseBooleanValue } from "../sdk-config.js";
