/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/gateway/auth.ts
/**
 * Gateway auth resolver re-export for Browser gateway modules.
 */
export { resolveGatewayAuth } from "../sdk-node-runtime.js";
