/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/gateway/net.ts
/**
 * Gateway network helper re-export for loopback host checks.
 */
export { isLoopbackHost } from "../sdk-node-runtime.js";
