/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/gateway/startup-auth.ts
/**
 * Gateway startup auth helper re-export for Browser plugin startup.
 */
export { ensureGatewayStartupAuth } from "../sdk-node-runtime.js";
