/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/logging/redact.ts
/**
 * Logging redaction helpers re-exported for Browser diagnostics.
 */
export { redactSensitiveText, redactToolPayloadText } from "../../../../shim/logging-core.js";
