/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/logging/subsystem.ts
/**
 * Subsystem logger factory re-exported for Browser modules.
 */
export { createSubsystemLogger } from "../../../../shim/logging-core.js";
