/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/cli/command-format.ts
/**
 * Re-export for CLI command formatting used by Browser setup/help output.
 */
export { formatCliCommand } from "../sdk-setup-tools.js";
