/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/media/store.ts
/**
 * Media storage helpers re-exported for Browser screenshots and artifacts.
 */
export { ensureMediaDir, saveMediaBuffer } from "../sdk-setup-tools.js";
