/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/sdk-config.ts
/**
 * Browser-local SDK config bridge plus Browser-specific default port helpers.
 */
import { normalizeOptionalLowercaseString } from "../../../shim/string-coerce-runtime.js";

export {
  getRuntimeConfig,
  getRuntimeConfigSnapshot,
  getRuntimeConfigSourceSnapshot,
} from "../../../shim/runtime-config-snapshot.js";
export { mutateConfigFile, replaceConfigFile } from "../../../shim/config-mutation.js";
export {
  type BrowserConfig,
  type BrowserProfileConfig,
  type OpenClawConfig,
} from "../../../shim/config-contracts.js";
export {
  normalizePluginsConfig,
  resolveEffectiveEnableState,
} from "../../../shim/plugin-config-runtime.js";
export { resolveGatewayPort } from "../../../shim/core.js";
export {
  CONFIG_DIR,
  escapeRegExp,
  resolveUserPath,
  shortenHomePath,
} from "../../../shim/text-utility-runtime.js";
type PortRange = { start: number; end: number };

const DEFAULT_BROWSER_CDP_PORT_RANGE_START = 18800;
const DEFAULT_BROWSER_CDP_PORT_RANGE_END = 18899;
const DEFAULT_BROWSER_CDP_PORT_RANGE_SPAN =
  DEFAULT_BROWSER_CDP_PORT_RANGE_END - DEFAULT_BROWSER_CDP_PORT_RANGE_START;

/** Default loopback port for the Browser control server. */
export const DEFAULT_BROWSER_CONTROL_PORT = 18791;

function isValidPort(port: number): boolean {
  return Number.isFinite(port) && port > 0 && port <= 65535;
}

function clampPort(port: number, fallback: number): number {
  return isValidPort(port) ? port : fallback;
}

function derivePort(base: number, offset: number, fallback: number): number {
  return clampPort(base + offset, fallback);
}

/** Derives the Browser control port from the gateway port. */
export function deriveDefaultBrowserControlPort(gatewayPort: number): number {
  return derivePort(gatewayPort, 2, DEFAULT_BROWSER_CONTROL_PORT);
}

/** Derives the managed Chrome CDP port range from the Browser control port. */
export function deriveDefaultBrowserCdpPortRange(browserControlPort: number): PortRange {
  const start = derivePort(browserControlPort, 9, DEFAULT_BROWSER_CDP_PORT_RANGE_START);
  const end = start + DEFAULT_BROWSER_CDP_PORT_RANGE_SPAN;
  if (end <= 65535) {
    return { start, end };
  }
  return {
    start: DEFAULT_BROWSER_CDP_PORT_RANGE_START,
    end: DEFAULT_BROWSER_CDP_PORT_RANGE_END,
  };
}

type BooleanParseOptions = {
  truthy?: string[];
  falsy?: string[];
};

const DEFAULT_TRUTHY = ["true", "1", "yes", "on"] as const;
const DEFAULT_FALSY = ["false", "0", "no", "off"] as const;

function matchesBooleanToken(value: string, tokens: readonly string[]): boolean {
  return tokens.includes(value);
}

/** Parses common string booleans with optional custom truthy/falsy tokens. */
export function parseBooleanValue(
  value: unknown,
  options: BooleanParseOptions = {},
): boolean | undefined {
  if (typeof value === "boolean") {
    return value;
  }
  if (typeof value !== "string") {
    return undefined;
  }
  const normalized = normalizeOptionalLowercaseString(value);
  if (!normalized) {
    return undefined;
  }
  const candidates: Array<[boolean, readonly string[]]> = [
    [true, options.truthy ?? DEFAULT_TRUTHY],
    [false, options.falsy ?? DEFAULT_FALSY],
  ];
  for (const [parsed, tokens] of candidates) {
    if (matchesBooleanToken(normalized, tokens)) {
      return parsed;
    }
  }
  return undefined;
}
