/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/sdk-setup-tools.ts
/**
 * Browser-local SDK setup/tooling bridge for CLI, media, and action helpers.
 */
export {
  callGatewayTool,
  listNodes,
  resolveNodeIdFromList,
  selectDefaultNodeFromList,
} from "../../../shim/agent-harness-runtime.js";
export type { AnyAgentTool, NodeListNode } from "../../../shim/agent-harness-runtime.js";
export {
  imageResultFromFile,
  jsonResult,
  readPositiveIntegerParam,
  readStringParam,
} from "../../../shim/channel-actions.js";
export { optionalStringEnum, stringEnum } from "../../../shim/channel-actions.js";
export {
  formatCliCommand,
  formatHelpExamples,
  inheritOptionFromParent,
  note,
  theme,
} from "../../../shim/cli-runtime.js";
export { danger, info } from "../../../shim/runtime-env.js";
export {
  IMAGE_REDUCE_QUALITY_STEPS,
  buildImageResizeSideGrid,
  getImageMetadata,
  isImageProcessorUnavailableError,
  resizeToJpeg,
} from "../../../shim/media-runtime.js";
export { detectMime } from "../../../shim/media-mime.js";
export { ensureMediaDir, saveMediaBuffer } from "../../../shim/media-runtime.js";
export { describeImageFile } from "../../../shim/media-understanding-runtime.js";
export { formatDocsLink } from "../../../shim/setup-tools.js";
