/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/utils.ts
/**
 * Browser utility re-exports for config paths, escaping, and user path resolution.
 */
export { CONFIG_DIR, escapeRegExp, resolveUserPath } from "./sdk-config.js";
