/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/browser/control-service.ts
/**
 * Browser control service barrel.
 *
 * Re-exports the background control service and shared control-state helpers
 * used by the plugin entrypoint, Gateway proxy, and tests.
 */
export {
  createBrowserControlContext,
  startBrowserControlServiceFromConfig,
} from "../control-service.js";
