/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/browser/safe-filename.ts
/**
 * Re-export for Browser download filename sanitization.
 */
export { sanitizeUntrustedFileName } from "../sdk-security-runtime.js";
