/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/browser/trash.ts
/**
 * Trash helpers for Browser-owned files constrained to user and OpenClaw temp
 * roots.
 */
import os from "node:os";
import { movePathToTrash as movePathToTrashWithAllowedRoots } from "../../../../shim/browser-config.js";
import { resolvePreferredOpenClawTmpDir } from "../../../../shim/temp-path.js";

/** Moves a path to trash only when it lives under allowed Browser roots. */
export async function movePathToTrash(targetPath: string): Promise<string> {
  return await movePathToTrashWithAllowedRoots(targetPath, {
    allowedRoots: [os.homedir(), resolvePreferredOpenClawTmpDir()],
  });
}
