/* eslint-disable */
// @generated by scripts/browser-runtime/sync.mjs — DO NOT EDIT.
// upstream: extensions/browser/src/config/paths.ts
/**
 * Browser config path helpers re-exported from the SDK config bridge.
 */
export { resolveGatewayPort } from "../sdk-config.js";
